### ISSUE TITLE
[ErrorException] unserialize(): Error at offset 219249 of 219250 bytes

### ISSUE THREAD

**Issue by MeikyuuTrader** [spatie/fork#22]
I'm trying to return an key-val array with UTF-8 characters. When running without, it outputs the array fine. Running with 2 files (0.556048 mb) it works fine. 

However, when running with 3+ files, 0.78592 mb, I get the unserialize error. 

```
Run Code

// Get Files
$files = Storage::files();

// Returns a key-val array 
$results = Fork::new()
    >run(
         fn() => $this->filesToWordFreq(array_slice($files, 0, 3)),
      );
```

With the debug below. 

```
   ErrorException 

  unserialize(): Error at offset 219249 of 219250 bytes

  at vendor/spatie/fork/src/Task.php:115
    111▕         $output = $this->output;
    112▕ 
    113▕         if (str_starts_with($output, self::SERIALIZATION_TOKEN)) {
    114▕             $output = unserialize(
  ➜ 115▕                 substr($output, strlen(self::SERIALIZATION_TOKEN))
    116▕             );
    117▕         }
    118▕ 
    119▕         return $output;

```

I've already increased my php memory limit, with `ini_set('memory_limit', '16384M');` earlier. 

Is there a hard limit to output size when using spatie/fork? As I was planning to run this with 27k files, not 3 just 3. 

# EDIT
When dumping the $output in output(), the value returned has been cut off. Does the output concatenation have some form of memory limit? 

```
        foreach ($this->connection->read() as $output) {
            $this->output .= $output;
        }
```

Dumping the variable in execute() has the entire string, so something goes wrong after the execute() function.

**Comment by MeikyuuTrader** [comment]
Issue fixed by using json_encode/json_decode instead of serialize. 

```
Task.php

public function execute() 
{
        return self::SERIALIZATION_TOKEN . json_encode($output);
}

public function output() 
{
        if (str_starts_with($output, self::SERIALIZATION_TOKEN)) {
            $output = json_decode(
                substr($output, strlen(self::SERIALIZATION_TOKEN)), true
            );
        }
}
```

Not the best solution per say, but my uft-8 key-val arrays can return normally now.

**Comment by MeikyuuTrader** [comment]
After a bit of searching, looks like the true issue was due the Connection.php either not having enough buffer size or timing out. 

I dramatically increased the buffer (128MB) and timeout and then it works fine. Not sure if the sereaialize was the issue, just kept the json encode/decode.
```
Connection.php

    protected function __construct(
        protected Socket $socket,
        protected int $bufferSize = 134217728,
        protected float $timeout = 30.0,
    ) {
```

**Comment by brendt** [comment]
This package wasn't designed for sending large payloads. It's meant to offload CPU-intensive tasks to separate processes. If you need to pass large amounts of data, you'll need to store that data in a persistent storage and only pass a reference to the main process.

If you need something more than this, you can look at https://github.com/spatie/async instead.

**Comment by MeikyuuTrader** [comment]
Ah my bad. I thought spatie/fork was for all concurrent php. Thanks for letting me know the proper package.
