### ISSUE TITLE
Undefined array key 51266

### ISSUE THREAD

**Issue by mahmoud-adel44** [spatie/fork#34]
Undefined array key 51266 
vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php
or this ,
Undefined array key 37790
at vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php : 
i get this errors when  i try to excute from get api request but when i make a laravel consol command  its works fine why is it ?

**Comment by SwithFr** [comment]
Found a solution ?
