### ISSUE TITLE
Endless loop outside of tests

### ISSUE THREAD

**Issue by lukeraymonddowning** [spatie/fork#4]
Sorry to bother you guys. I'm actively looking for a fix for this and trying a bunch of stuff but a problem shared...

So, I'm using a MacBook Pro 2020 Intel variant. I run Laravel locally using Valet. My test suite is obviously using PHP to run as you'd expect. I'm on the latest version of valet and I'm using PHP 8.0.5.

When I run my test suite, I get the expected result:

```php
$test = Fork::new()->run(fn() => 'Hello', fn() => 'World');
dd($test);
```

<img width="899" alt="Screenshot 2021-04-30 at 22 07 36" src="https://user-images.githubusercontent.com/12202279/116754344-7aafde00-aa00-11eb-970d-dfd4296d79c4.png">

So far, so breezy. However, if I switch to the browser and hit a route that calls this code, the `dd` never takes place.

I've done some debugging (mainly by placing `ray` calls at various points in the `Fork` class), and the issue seems to stem from the call to `pcntl_waitpid` in `Task` on line 133. For whatever reason, in the browser, this always returns a status code of 0. The output on line 131 gets set correctly, but it still doesn't return the PID to say it has completed the closure.

Thanks for all your hard work! I'll keep looking into this from my end.

**Comment by dhrrgn** [comment]
PCNTL should only be used in the CLI. 

Per [the docs](https://www.php.net/manual/en/intro.pcntl.php):

> Process Control should not be enabled within a web server environment and unexpected results may happen if any Process Control functions are used within a web server environment.

The behavior you are experiencing is is because the process you are forking is the php-fpm process...which is always going to cause weird things to happen.

**Comment by dhrrgn** [comment]
@freekmurze May be worth adding a note in the README about this.  Maybe even add a check like:

```php
if (php_sapi_name() !== 'cli') {
    throw new RuntimeException('Process forking is only supported in CLI mode');
}
```

**Comment by lukeraymonddowning** [comment]
Doh! Sorry about this 🤦🏼‍♂️ Thanks for the info!

**Comment by freekmurze** [comment]
We should definitely mention in the readme that it doesn't word in a web context.
I'm a bit torn what we should do when this code is executed in a web context: throw an exception like suggested or above, or silently execute all given closures without concurrency. 

@brendt What do you think?

**Comment by brendt** [comment]
Definitely throw an exception :) I'll make the necessary changes.

**Comment by brendt** [comment]
Done: https://github.com/spatie/fork/releases/tag/1.0.1

**Comment by jasonvarga** [comment]
Sorry to comment on a closed issue.

`function_exists('pcntl_fork')` returns `true` in my browser. (At least, when using Valet)

https://github.com/spatie/fork/commit/6c4c56c451ea36265ed276642e16314fe4b3dcea
